// Auto-generated by OpenLane
module alu32(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[31:0] A,
  input[31:0] B,
  input[4:0] alu_opcode,
  output[31:0] Result,
  output Z,
  output N,
  output C,
  output P,
  output V
);
endmodule
